<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "sqllog"
 *
 * Auto generated by Extension Builder 2020-02-20
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'sqllog',
    'description' => 'A small extension that extends Database/Conneection with  SQL-Logging',
    'category' => 'plugin',
    'author' => 'Peter Niederlag',
    'author_email' => 'peter.niederlag@datenbetrieb.de',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-10.4.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
